### ISSUE TITLE
Probleme PatrOwlEngine OpenVAS

### ISSUE THREAD

**Issue by GaetCAN** [Patrowl/PatrowlDocs#40] opened 2023-12-04 09:43 UTC
Hello 
In the first image, it's when I barely arrive at the Login page of the OpenVAS administration without having entered any information in the inputs:
![OpenVas1](https://github.com/Patrowl/PatrowlDocs/assets/152167260/a151c956-a739-44ca-a753-d3ec89be26b3)

The second image is when I entered my ID and password, so I can't reach the OpenVAS admin interface :

![OpenVAS2](https://github.com/Patrowl/PatrowlDocs/assets/152167260/54cf31b3-0865-4978-98c8-02c8fbb00746)

Could you help me solve this problem please?
Thank you.

**Comment by MaKyOtOx** [comment] 2023-12-04 09:49
Hello @GaetCAN 
I will close this issue cause it seems the issue is related to the installation of Greenbone / OpenVAS.
Btw, we published an installation script here to help users to install it: https://makyotox.medium.com/install-openvas-greenbone-20-08-on-ubuntu-20-04-8082c7eab67c
Could be useful

**Closed as completed by MaKyOtOx** 2023-12-04 09:49 UTC
